/* 
 * Telegram service API
 *
 * Using the API for Telegram chatbots, you can integrate your system with SendPulse’s chatbots service and get detailed information about your account, bots, subscribers, variables, flows, and chats. You can also create campaigns, launch flows, assign and remove variables and tags.               On the right, there is a button for authorizing requests made on this page. Click “Authorize,” then insert the ID and Secret from your account.               To perform a request directly from the page, click the \"Try it out\" button within each method block. Then fill in input fields if any (for URL parameters, the description is right below the URL request; for body parameters, the description is under the “Scheme” button to the right of the example), and click “Run.” You'll find the server response and description of received parameters below.         
 *
 * OpenAPI spec version: 1.0.0
 * Contact: justin@justinwritescode.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SendPulse.Api.Client.SwaggerDateConverter;

namespace SendPulse.Api.Model
{
    /// <summary>
    /// InlineResponse2006Data
    /// </summary>
    [DataContract]
        internal partial class InlineResponse2006Data :  IEquatable<InlineResponse2006Data>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2006Data" /> class.
        /// </summary>
        /// <param name="subscribedTotalCount">subscribedTotalCount.</param>
        /// <param name="subscribedActiveCount">subscribedActiveCount.</param>
        /// <param name="outgoingMessagesTotalCount">outgoingMessagesTotalCount.</param>
        public InlineResponse2006Data(int? subscribedTotalCount = default(int?), int? subscribedActiveCount = default(int?), int? outgoingMessagesTotalCount = default(int?))
        {
            this.SubscribedTotalCount = subscribedTotalCount;
            this.SubscribedActiveCount = subscribedActiveCount;
            this.OutgoingMessagesTotalCount = outgoingMessagesTotalCount;
        }
        
        /// <summary>
        /// Gets or Sets SubscribedTotalCount
        /// </summary>
        [DataMember(Name="subscribedTotalCount", EmitDefaultValue=true)]
        public int? SubscribedTotalCount { get; set; }

        /// <summary>
        /// Gets or Sets SubscribedActiveCount
        /// </summary>
        [DataMember(Name="subscribedActiveCount", EmitDefaultValue=true)]
        public int? SubscribedActiveCount { get; set; }

        /// <summary>
        /// Gets or Sets OutgoingMessagesTotalCount
        /// </summary>
        [DataMember(Name="outgoingMessagesTotalCount", EmitDefaultValue=true)]
        public int? OutgoingMessagesTotalCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2006Data {\n");
            sb.Append("  SubscribedTotalCount: ").Append(SubscribedTotalCount).Append("\n");
            sb.Append("  SubscribedActiveCount: ").Append(SubscribedActiveCount).Append("\n");
            sb.Append("  OutgoingMessagesTotalCount: ").Append(OutgoingMessagesTotalCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2006Data);
        }

        /// <summary>
        /// Returns true if InlineResponse2006Data instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2006Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2006Data input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SubscribedTotalCount == input.SubscribedTotalCount ||
                    (this.SubscribedTotalCount != null &&
                    this.SubscribedTotalCount.Equals(input.SubscribedTotalCount))
                ) && 
                (
                    this.SubscribedActiveCount == input.SubscribedActiveCount ||
                    (this.SubscribedActiveCount != null &&
                    this.SubscribedActiveCount.Equals(input.SubscribedActiveCount))
                ) && 
                (
                    this.OutgoingMessagesTotalCount == input.OutgoingMessagesTotalCount ||
                    (this.OutgoingMessagesTotalCount != null &&
                    this.OutgoingMessagesTotalCount.Equals(input.OutgoingMessagesTotalCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubscribedTotalCount != null)
                    hashCode = hashCode * 59 + this.SubscribedTotalCount.GetHashCode();
                if (this.SubscribedActiveCount != null)
                    hashCode = hashCode * 59 + this.SubscribedActiveCount.GetHashCode();
                if (this.OutgoingMessagesTotalCount != null)
                    hashCode = hashCode * 59 + this.OutgoingMessagesTotalCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
