/*
 * Telegram service API
 *
 * Using the API for Telegram chatbots, you can integrate your system with SendPulse’s chatbots service and get detailed information about your account, bots, subscribers, variables, flows, and chats. You can also create campaigns, launch flows, assign and remove variables and tags.               On the right, there is a button for authorizing requests made on this page. Click “Authorize,” then insert the ID and Secret from your account.               To perform a request directly from the page, click the \"Try it out\" button within each method block. Then fill in input fields if any (for URL parameters, the description is right below the URL request; for body parameters, the description is under the “Scheme” button to the right of the example), and click “Run.” You'll find the server response and description of received parameters below.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: justin@justinwritescode.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = SendPulse.Api.Client.SwaggerDateConverter;

namespace SendPulse.Api.Models
{
    /// <summary>
    /// Contact
    /// </summary>
    [DataContract]
    public partial class Contact : IEquatable<Contact>, IValidatableObject
    {
        /// <summary>
        ///                      * &#x60;1&#x60; - active                      * &#x60;2&#x60; - unsubscribed                      * &#x60;3&#x60; - disabled                      * &#x60;4&#x60; - blocked by user
        /// </summary>
        /// <value>                     * &#x60;1&#x60; - active                      * &#x60;2&#x60; - unsubscribed                      * &#x60;3&#x60; - disabled                      * &#x60;4&#x60; - blocked by user                  </value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public ContactStatusEnum? Status { get; set; }

        ///// <summary>
        ///// Initializes a new instance of the <see cref="Contact" /> class.
        ///// </summary>
        ///// <param name="id">id.</param>
        ///// <param name="botId">botId.</param>
        ///// <param name="status">                     * &#x60;1&#x60; - active                      * &#x60;2&#x60; - unsubscribed                      * &#x60;3&#x60; - disabled                      * &#x60;4&#x60; - blocked by user                  .</param>
        ///// <param name="channelData">channelData.</param>
        ///// <param name="tags">tags.</param>
        ///// <param name="variables">variable_name: variable_value.</param>
        ///// <param name="isChatOpened">isChatOpened.</param>
        ///// <param name="lastActivityAt">lastActivityAt.</param>
        ///// <param name="automationPausedUntil">automationPausedUntil.</param>
        ///// <param name="createdAt">createdAt.</param>
        //public Contact(string id = default(string), string botId = default(string), ContactStatusEnum? status = default(ContactStatusEnum?), ContactChannelData channelData = default(ContactChannelData), Collection<string> tags = default(Collection<string>), object variables = default(object), bool? isChatOpened = default(bool?), DateTime? lastActivityAt = default, DateTime? automationPausedUntil = default, DateTime? createdAt = default, Uri? subscribeUrl = default)
        //{
        //    this.Id = id;
        //    this.BotId = botId;
        //    this.Status = status;
        //    this.ChannelData = channelData;
        //    this.Tags = tags;
        //    this.Variables = new StringDictionary(variables as IStringDictionary);
        //    this.IsChatOpened = isChatOpened;
        //    this.LastActivityAt = lastActivityAt ?? DateTime.UtcNow;
        //    this.AutomationPausedUntil = automationPausedUntil ?? DateTime.MinValue.ToUniversalTime();
        //    this.CreatedAt = createdAt ?? DateTime.MinValue.ToUniversalTime();
        //    this.SubscribeUrl = subscribeUrl;
        //}

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        [JProp("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets BotId
        /// </summary>
        [DataMember(Name = "bot_id", EmitDefaultValue = true)]
        [JProp("bot_id")]
        public string BotId { get; set; }

        /// <summary>
        /// Gets or Sets ChannelData
        /// </summary>
        [DataMember(Name = "channel_data", EmitDefaultValue = true)]
        [JProp("channel_data")]
        public ContactChannelData ChannelData { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", EmitDefaultValue = true)]
        public Collection<string> Tags { get; set; }

        /// <summary>
        /// variable_name: variable_value
        /// </summary>
        /// <value>variable_name: variable_value</value>
        [DataMember(Name = "variables", EmitDefaultValue = true)]
        public StringObjectDictionary Variables { get; set; }

        /// <summary>
        /// Gets or Sets IsChatOpened
        /// </summary>
        [DataMember(Name = "is_chat_opened", EmitDefaultValue = true)]
        [JProp("is_chat_opened")]
        public bool? IsChatOpened { get; set; }

        /// <summary>
        /// Gets or Sets LastActivityAt
        /// </summary>
        [DataMember(Name = "last_activity_at", EmitDefaultValue = true)]
        [JProp("last_activity_at")]
        public DateTime? LastActivityAt { get; set; }

        /// <summary>
        /// Gets or Sets AutomationPausedUntil
        /// </summary>
        [DataMember(Name = "automation_paused_until", EmitDefaultValue = true)]
        [JProp("automation_paused_until")]
        public DateTime? AutomationPausedUntil { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", EmitDefaultValue = true)]
        [JProp("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets TelegramId
        /// </summary>
        [DataMember(Name = "telegram_id", EmitDefaultValue = true)]
        [JProp("telegram_id")]
        public long? TelegramId { get; set; }

        [DataMember(Name = "subscribe_url", EmitDefaultValue = true)]
        public Uri? SubscribeUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>string presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Contact {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  BotId: ").Append(BotId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ChannelData: ").Append(ChannelData).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("  IsChatOpened: ").Append(IsChatOpened).Append("\n");
            sb.Append("  LastActivityAt: ").Append(LastActivityAt).Append("\n");
            sb.Append("  AutomationPausedUntil: ").Append(AutomationPausedUntil).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  TelegramId: ").Append(TelegramId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Contact);
        }

        /// <summary>
        /// Returns true if Contact instances are equal
        /// </summary>
        /// <param name="input">Instance of Contact to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Contact input)
        {
            if (input == null)
                return false;

            return (this.Id == input.Id || (this.Id != null && this.Id.Equals(input.Id)))
                && (
                    this.BotId == input.BotId
                    || (this.BotId != null && this.BotId.Equals(input.BotId))
                )
                && (
                    this.Status == input.Status
                    || (this.Status != null && this.Status.Equals(input.Status))
                )
                && (
                    this.ChannelData == input.ChannelData
                    || (this.ChannelData != null && this.ChannelData.Equals(input.ChannelData))
                )
                && (
                    this.Tags == input.Tags
                    || this.Tags != null
                        && input.Tags != null
                        && this.Tags.SequenceEqual(input.Tags)
                )
                && (
                    this.Variables == input.Variables
                    || (this.Variables != null && this.Variables.Equals(input.Variables))
                )
                && (
                    this.IsChatOpened == input.IsChatOpened
                    || (this.IsChatOpened != null && this.IsChatOpened.Equals(input.IsChatOpened))
                )
                && (
                    this.LastActivityAt == input.LastActivityAt
                    || (
                        this.LastActivityAt != null
                        && this.LastActivityAt.Equals(input.LastActivityAt)
                    )
                )
                && (
                    this.AutomationPausedUntil == input.AutomationPausedUntil
                    || (
                        this.AutomationPausedUntil != null
                        && this.AutomationPausedUntil.Equals(input.AutomationPausedUntil)
                    )
                )
                && (
                    this.CreatedAt == input.CreatedAt
                    || (this.CreatedAt != null && this.CreatedAt.Equals(input.CreatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.BotId != null)
                    hashCode = hashCode * 59 + this.BotId.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.ChannelData != null)
                    hashCode = hashCode * 59 + this.ChannelData.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                if (this.Variables != null)
                    hashCode = hashCode * 59 + this.Variables.GetHashCode();
                if (this.IsChatOpened != null)
                    hashCode = hashCode * 59 + this.IsChatOpened.GetHashCode();
                if (this.LastActivityAt != null)
                    hashCode = hashCode * 59 + this.LastActivityAt.GetHashCode();
                if (this.AutomationPausedUntil != null)
                    hashCode = hashCode * 59 + this.AutomationPausedUntil.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            yield break;
        }

        [JExtension]
        public JExtensionDict ExtensionData { get; set; }
    }
}
